# Site settings
title: Geothermal Energy
description: Geothermal energy is heat energy generated and stored in the Earth. Thermal energy is the energy that determines the temperature of matter.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "" # the subpath of your site, e.g. /blog/ or / for root
url: "https://lubarry.github.io/Geothermal-Energy/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: Barry #github username
repo: Barry #github repository
branch: master #branch
relative_source: ../Geothermal-Energy/ #source directory
destination: ../Geothermal-Energy/ #destination directory
production_url:  
source_url: https://lubarry.github.io/Geothermal-Energy/ #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
